### After making required changes, save the file and run `termux-reload-settings`
# extra-keys-style = default

### Force capitalize all text in extra keys row button labels.
# extra-keys-text-all-caps = true

### Two rows with more keys
extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'], \
               ['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]

### Configuration with additional popup keys (swipe up from an extra key)
# extra-keys = [[ \
#   {key: ESC, popup: {macro: "CTRL f d", display: "tmux exit"}}, \
#   {key: CTRL, popup: {macro: "CTRL f BKSP", display: "tmux ←"}}, \
#   {key: ALT, popup: {macro: "CTRL f TAB", display: "tmux →"}}, \
#   {key: TAB, popup: {macro: "ALT a", display: A-a}}, \
#   {key: LEFT, popup: HOME}, \
#   {key: DOWN, popup: PGDN}, \
#   {key: UP, popup: PGUP}, \
#   {key: RIGHT, popup: END}, \
#   {macro: "ALT j", display: A-j, popup: {macro: "ALT g", display: A-g}}, \
#   {key: KEYBOARD, popup: {macro: "CTRL d", display: exit}} \
# ]]

### Another configuration with advanced popup key usage designed for more
### specific use-cases. In this case, it is designed for working with Vim-like
### editors for faster navigation
#extra-keys = [ \
#  [ \
#    { key: ESC, popup: { macro: ":q\n", display: "QuickExit" } }, \
#    { key: '/', popup: '\\\\' }, \
#    { key: '-', popup: '_' }, \
#    { key: HOME, popup: { macro: "CTRL HOME", display: "Top" } }, \
#    { key: UP, popup: { macro: "CTRL UP", display: "UP" } }, \
#    { key: END, popup: { macro: "CTRL END", display: "End" } }, \
#    { key: ":", popup: ";" }, \
#    { key: "(", popup: "{" } \
#  ], \
#  [ \
#    { key: TAB, popup: { macro: ":wq\n", display: "Write And Exit" } }, \
#    { key: CTRL, popup: { macro: ":w\n", display: "Write" } }, \
#    ALT, \
#    { key: LEFT, popup: { macro: "CTRL LEFT", display: "Left" } }, \
#    { key: DOWN, popup: { macro: "CTRL DOWN", display: "Bottom" } }, \
#    { key: RIGHT, popup: { macro: "CTRL RIGHT", display: "Right" } }, \
#    { key: "#", popup: "$" }, \
#    { key: ")", popup: "}" } \
#  ] \
#]

bell-character = ignore
back-key=escape
